site_name: Library Policy and Proceedures

theme: readthedocs
extra_css: [extra.css]

# pages:
# - Home: 'index.md'
# - Archives:
#     - 'Writing your docs': 'archives/writing-your-docs.md'
#     - 'Styling your docs': 'archives/styling-your-docs.md'
# - About:
#     - 'License': 'about/license.md'
#     - 'Release Notes': 'about/release-notes.md'
